language: python

env:
  global:
    PIP_PREFER_BINARY=true # https://github.com/numba/llvmlite/issues/471

matrix:
  include:

    - os: linux
      sudo: required
      services: docker
      python: '2.7'

      #  - "3.3" # failed due to setuptool version
      #  - "3.4" # failed due to numba (llvmlite)

    - os: linux
      sudo: required
      services: docker
      python: '3.5'

    - os: linux
      sudo: required
      services: docker
      python: '3.6'

    - os: linux
      dist: xenial
      sudo: required
      services: docker
      python: '3.7'


install:
  - pip install --upgrade pip
  - pip install -r requirements_ci.txt

script:
    # Show the 20 slowest running tests
  - pytest --cov=pyod/ --durations=20 --disable-warnings

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - yzhao062@gmail.com
  on_success: never # default: change
  on_failure: always # default: always
